GitCandy/Controllers/SettingController.cs
using GitCandy.App_GlobalResources;
using GitCandy.Configuration;
using GitCandy.Filters;
using GitCandy.Git;
using GitCandy.Log;
using GitCandy.Models;
using System;
using System.Composition;
using System.Web;
using System.Web.Mvc;

namespace GitCandy.Controllers
{
    [Administrator]
    [Export(typeof(SettingController))]
    public class SettingController : CandyControllerBase
    {
        public ActionResult Edit()
        {
            var config = UserConfiguration.Current;
            var model = new SettingModel
            {
                IsPublicServer = config.IsPublicServer,
                ForceSsl = config.ForceSsl,
                SslPort = config.SslPort,
                LocalSkipCustomError = config.LocalSkipCustomError,
                AllowRegisterUser = config.AllowRegisterUser,
                AllowRepositoryCreation = config.AllowRepositoryCreation,
                RepositoryPath = config.RepositoryPath,
                CachePath = config.CachePath,
                GitExePath = config.GitExePath,
                NumberOfCommitsPerPage = config.NumberOfCommitsPerPage,
                NumberOfItemsPerList = config.NumberOfItemsPerList,
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SettingModel model)
        {
            var needRestart = false;

            if (ModelState.IsValid)
            {
                var verify = GitService.VerifyGit(model.GitExePath);
                if (!verify)
                {
                    ModelState.AddModelError("GitExePath", string.Format(SR.Validation_Filepath, "GitExePath", "git.exe"));
                    return View(model);
                }

                var config = UserConfiguration.Current;

                needRestart = (config.CachePath != model.CachePath);

                config.IsPublicServer = model.IsPublicServer;
                config.ForceSsl = model.ForceSsl;
                config.SslPort = model.SslPort;
                config.LocalSkipCustomError = model.LocalSkipCustomError;
                config.AllowRegisterUser = model.AllowRegisterUser;
                config.AllowRepositoryCreation = model.AllowRepositoryCreation;
                config.RepositoryPath = model.RepositoryPath;
                config.CachePath = model.CachePath;
                config.GitExePath = model.GitExePath;
                config.NumberOfCommitsPerPage = model.NumberOfCommitsPerPage;
                config.NumberOfItemsPerList = model.NumberOfItemsPerList;
                config.Save();
                ModelState.Clear();
            }

            Logger.Info("Settings updated by {0}#{1}", Token.Username, Token.UserID);

            if (needRestart)
            {
                HttpRuntime.UnloadAppDomain();
            }

            return View(model);
        }

        public ActionResult Restart(string conform)
        {
            if (string.Equals(conform, "yes", StringComparison.OrdinalIgnoreCase))
            {
                HttpRuntime.UnloadAppDomain();
                return RedirectToStartPage();
            }
            return View();
        }
    }
}

GitCandy/Views/Setting/Edit.cshtml
@model GitCandy.Models.SettingModel

@{
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, SR.Setting_EditTitle);
}

<h4>@SR.Setting_EditTitle</h4>

<div class="span10">
    @using (Html.BeginForm("Edit", "Setting", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="row">
            @Html.LabelFor(s => s.IsPublicServer, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            <div class="switch switch-small" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.IsPublicServer)
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(s => s.ForceSsl, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            <div class="switch switch-small" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.ForceSsl)
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(s => s.SslPort, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.SslPort, new { @class = "span4 text-left lead" })
        </div>

        <div class="row">
            @Html.LabelFor(s => s.LocalSkipCustomError, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            <div class="switch switch-small" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.LocalSkipCustomError)
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(s => s.AllowRegisterUser, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            <div class="switch switch-small" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.AllowRegisterUser)
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(s => s.AllowRepositoryCreation, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            <div class="switch switch-small" data-on-label="@SR.Shared_Yes" data-off-label="@SR.Shared_No">
                @Html.CheckBoxFor(s => s.AllowRepositoryCreation)
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(s => s.RepositoryPath, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.RepositoryPath, new { @class = "span4 text-left lead" })
        </div>

        <div class="row">
            @Html.LabelFor(s => s.CachePath, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.CachePath, new { @class = "span4 text-left lead" })
        </div>

        <div class="row">
            @Html.LabelFor(s => s.GitExePath, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.GitExePath, new { @class = "span4 text-left lead" })
        </div>

        <div class="row">
            @Html.LabelFor(s => s.NumberOfCommitsPerPage, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.NumberOfCommitsPerPage, new { @class = "span4 text-left lead" })
        </div>

        <div class="row">
            @Html.LabelFor(s => s.NumberOfItemsPerList, new { @class = "span4 text-right lead muted" })
            <span class="span1"></span>
            @Html.TextBoxFor(s => s.NumberOfItemsPerList, new { @class = "span4 text-left lead" })
        </div>

        if (!ViewData.ModelState.IsValid)
        {
        @Html.ValidationSummary(SR.Setting_UpdateSettingsUnsuccessfull, new { @class = "alert alert-error" })
        }

        <div class="form-actions">
            <div class="pull-left">
                @Html.ActionLink(SR.Shared_Restart, "Restart", null, new { @class = "btn" })
            </div>
            <div class="pull-right">
                <button type="reset" class="btn btn-inverse">@SR.Shared_Reset</button>
                <button type="submit" class="btn btn-primary">@SR.Shared_Save</button>
            </div>
        </div>
    }
</div>

GitCandy/Views/Setting/Restart.cshtml
@{
    ViewBag.Title = string.Format(SR.Shared_TitleFormat, string.Format(SR.Setting_RestartTitle));
}

<h4>@string.Format(SR.Setting_RestartTitle)</h4>

<div class="span7">
    <div class="alert alert-block">
        <h4>@SR.Shared_Conform</h4>
        @string.Format(SR.Setting_RestartWords);
    </div>

    <div class="form-actions">
        <div class="pull-left">
            @Html.ActionLink(SR.Shared_Back, "Edit", "Setting", null, new { @class = "btn" })
        </div>
        <div class="pull-right">
            @Html.ActionLink(SR.Shared_Restart, "Restart", "Setting", new { Conform = "Yes" }, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>